export enum GATEWAY_PAYMENT_STATUS {
  'APPROVED' = 'APPROVED',
  'PENDING' = 'PENDING',
  'INSUFFICIENT_FUNDS' = 'INSUFFICIENT_FUNDS',
  'INVALID_CARD' = 'INVALID_CARD',
  'EXPIRED_CARD' = 'EXPIRED_CARD',
  'CARD_NOT_ACTIVATED' = 'CARD_NOT_ACTIVATED',
  'FRAUD_SUSPECTED' = 'FRAUD_SUSPECTED',
  'DECLINED' = 'DECLINED',
  'UNKNOWN_ERROR' = 'UNKNOWN_ERROR',
}
